# Generated by Django 4.2.7 on 2025-11-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parameter', models.CharField(choices=[('flowrate', 'Flowrate'), ('pressure', 'Pressure'), ('temperature', 'Temperature')], max_length=50)),
                ('condition', models.CharField(choices=[('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('equals', 'Equals'), ('between', 'Between')], max_length=50)),
                ('threshold', models.FloatField()),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('send_email', models.BooleanField(default=False)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('send_telegram', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment.equipment')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='equipment.alertrule')),
            ],
            options={
                'verbose_name_plural': 'Alert histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
